include(FetchContent)
find_package(Eigen3 CONFIG QUIET)
if(NOT TARGET Eigen3::Eigen)
  if(EXISTS "${CMAKE_SOURCE_DIR}/.deps/eigen/Eigen/Core")
    add_library(mvo_eigen INTERFACE)
    target_include_directories(mvo_eigen SYSTEM INTERFACE "${CMAKE_SOURCE_DIR}/.deps/eigen")
    add_library(Eigen3::Eigen ALIAS mvo_eigen)
  else()
    set(EIGEN_BUILD_DOC OFF CACHE BOOL "" FORCE)
    set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(eigen GIT_REPOSITORY https://gitlab.com/libeigen/eigen.git GIT_TAG 5.0.0 GIT_SHALLOW TRUE)
    FetchContent_MakeAvailable(eigen)
  endif()
endif()
find_package(highs CONFIG QUIET)
if(NOT TARGET highs::highs AND NOT TARGET highs)
  set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
  set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
  set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
  set(BUILD_CXX_EXAMPLE OFF CACHE BOOL "" FORCE)
  set(FAST_BUILD ON CACHE BOOL "" FORCE)
  set(ZLIB OFF CACHE BOOL "" FORCE)
  if(EXISTS "${CMAKE_SOURCE_DIR}/.deps/HiGHS-1.11.0/CMakeLists.txt")
    add_subdirectory(.deps/HiGHS-1.11.0 ${CMAKE_BINARY_DIR}/deps/highs EXCLUDE_FROM_ALL)
  else()
    FetchContent_Declare(highs URL https://codeload.github.com/ERGO-Code/HiGHS/tar.gz/refs/tags/v1.11.0 URL_HASH SHA256=2b44b074cf41439325ce4d0bbdac2d51379f56faf17ba15320a410d3c1f07275)
    FetchContent_MakeAvailable(highs)
  endif()
endif()
find_package(NLopt CONFIG QUIET)
if(NOT TARGET NLopt::nlopt AND NOT TARGET nlopt)
  set(NLOPT_CXX ON CACHE BOOL "" FORCE)
  foreach(lang PYTHON OCTAVE MATLAB GUILE JAVA SWIG FORTRAN TESTS)
    set(NLOPT_${lang} OFF CACHE BOOL "" FORCE)
  endforeach()
  if(EXISTS "${CMAKE_SOURCE_DIR}/.deps/nlopt/CMakeLists.txt")
    add_subdirectory(.deps/nlopt ${CMAKE_BINARY_DIR}/deps/nlopt EXCLUDE_FROM_ALL)
  else()
    FetchContent_Declare(nlopt GIT_REPOSITORY https://github.com/stevengj/nlopt.git GIT_TAG v2.11.0 GIT_SHALLOW TRUE)
    FetchContent_MakeAvailable(nlopt)
  endif()
endif()
